version: "3.9"

networks:
  proxy-network:
    external: true
  elk-network: {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    restart: always
    networks:
      - elk-network
    ports:
      - 9200:9200 # for REST API
      - 9300:9300 # for inter-node communication
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false # disable security, not recommended for production

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    restart: always
    networks:
      - elk-network
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
